import { StyleSheet } from "react-native";

export const getStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flexGrow: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.background,
      padding: 20,
    },
    title: {
      fontSize: 28,
      fontWeight: "bold",
      marginBottom: 4,
      color: colors.textPrimary,
    },
    subtitle: {
      fontSize: 16,
      color: colors.textSecondary,
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.textPrimary,
      marginBottom: 12,
      textAlign: "left",
      width: "100%",
    },
    userTypeContainer: {
      display:"flex",
      alignItems:"center",
      width: "100%",
      marginBottom: 20,
    },
    userTypeButtons: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
    },
    userTypeButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      backgroundColor: colors.card,
      marginHorizontal: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    userTypeButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    userTypeButtonText: {
      fontSize: 14,
      fontWeight: "500",
      color: colors.textSecondary,
      marginLeft: 8,
    },
    userTypeButtonTextActive: {
      color: colors.onPrimary,
    },
    shopOwnerContainer: {
      width: "100%",
      marginBottom: 10,
    },
    input: {
            width: "100%",
      height: 50,
      backgroundColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 15,
      fontSize: 15,
      marginBottom: 16,
      color: colors.textPrimary,
    },
    textArea: {
      height: 80,
      textAlignVertical: "top",
      paddingTop: 12,
    },
    button: {
      backgroundColor: colors.primary,
      paddingVertical: 14,
      borderRadius: 8,
      width: "100%",
      alignItems: "center",
      marginBottom: 16,
      marginTop: 16,
    },
    buttonText: {
      color: colors.onPrimary,
      fontSize: 18,
      fontWeight: "bold",
    },
    loginContainer: {
      flexDirection: "row",
      marginTop: 10,
    },
    loginText: {
      fontSize: 14,
      color: colors.textPrimary,
    },
    loginLink: {
      fontSize: 14,
      color: colors.primary,
      fontWeight: "bold",
    },
    mapTrigger: {
      backgroundColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: "#ccc",
      marginBottom: 12,
    },
    mapTriggerTxt: {
      color: colors.textPrimary,
      marginLeft: 8,
      fontSize: 14,
    },
    mapButtons: {
      position: "absolute",
      bottom: 40,
      left: 20,
      right: 20,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    mapBtn: {
      backgroundColor: "#fff",
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
    },
    mapBtnPrimary: {
      backgroundColor: "#007aff",
    },
    mapBtnTxt: {
      color: "#000",
      fontWeight: "600",
    },
    mapBtnTxtLight: {
      color: "#fff",
    },
    imageRow: {
      flexDirection: "row",
      marginVertical: 10,
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
    },
    imageButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.border,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 8,
      width: "50%",
      height: 50,
    },
    imageBtnTxt: {
      marginLeft: 6,
      color: colors.textPrimary,
      fontSize: 14,
    },
    previewWrap: {
      alignSelf: "center",
      marginVertical: 10,
    },
    preview: {
      width: 100,
      borderRadius: 20,
      height: 100,
    },
    removeBadge: {
      position: "absolute",
      top: -4,
      right: -4,
      backgroundColor: "rgba(0,0,0,0.6)",
      borderRadius: 11,
    },
  });
